trigger:
- master
- staging

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- pwsh:  ./setBuildName.ps1 $(Build.BuildId)
  displayName: 'Set Build Name'

- script: |
    npm install
  displayName: 'npm install'

- task: Npm@1
  inputs:
    command: custom
    customCommand: run build-prod
  displayName: 'Build React Files'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'build' 
    artifactName: 'reactDrop'
