export class AnalyticsEvent {
  static unknown = 'Unknown';
  static appLoad = 'App_Load';
  static homeView = 'Home_Page_View';
  static darkMode = 'DarkMode';
  static lightMode = 'LightMode';
  // _AdMob
  static addMobDonationPage = 'Donation_Ad_View';
  static addMobDonationPageClose = 'Donation_Ad_Close';
  static addMobDonationPageClick = 'Donation_Ad_Click';
  static addMobDonationPageClickBeforeReady = 'Donation_Ad_Click_before_the_ad_has_loaded';
  static addMobDonationPageFailedToLoad = 'Donation_Ad_failed_to_load';
  // pages
  static aboutPage = 'About_Page_View';
  static rawMaterialPage = 'RawMaterial_Page_View';
  static productsPage = 'Product_Page_View';
  static curiositiesPage = 'Curiosity_Page_View';
  static genericPage = 'Generic_Page_View';
  static genericSearchPage = 'Generic_Search_Page_View';
  static genericAllRequiredRawMaterialsPage = 'Generic_Page_with_all_of_the_RawMaterials_View';
  static genericPageRefinerRecipe = 'Generic_Refiner_Recipe_Page_View';
  static allPossibleOutputsPage = 'All_Possible_Outputs_Page_View';
  static donationPage = 'Donation_Page_Page_View';
  static refinerRecipePage = 'Refiner_Recipe_Page_View';
  static languageHelpPage = 'Language_Help_Page_View';
  static cartPage = 'Cart_Page_View';
  static cookingPage = 'Cooking_Page_View';
  static nutrientProcessorRecipePage = 'Nutrient_Processor_Recipe_Page_View';
  static exploitPage = 'Exploit_Page_View';
  static exploitDetailsPage = 'Exploit_Details_Page_View';
  static buildingsPage = 'Buildings_Page_View';
  static portalPage = 'Portal_Page_View';
  static addPortalPage = 'Add_Portal_Page_View';
  static viewPortalPage = 'View_Portal_Page_View';
  static advancedSeachPage = 'Advanced_Search_Page_View';
  static guidePage = 'Guide_Page_View';
  static guideDetailsPage = 'Guide_Details_Page_View';
  static settingsPage = 'Settings_Page_View';
  static appleMenuPage = 'Apple_Menu_Page_View';
  static releasesPage = 'Releases_Page_View';
  static helloGamesPage = 'HelloGames_Page_View';
  static newsPage = 'News_Page_View';
  static processorRecipePage = 'Processor_Recipe_Page_View';
  static contributorsPage = 'Contributors_Page_View';
  static communityMissionPage = 'Community_Mission_Page_View';
  static imageViewerPage = 'Image_Viewer_Page_View';
  // user_events
  static addToCartFromHome = 'Added_item_to_cart_from_Home_Page';
  static exploitItemClick = 'Exploit_item_Click';
  // json
  static loadRawMaterialJson = 'Loaded_RawMaterials.json';
  static loadProductJson = 'Loaded_Products.json';
  static loadTradeItemsJson = 'Loaded_TradeItems.json';
  static loadOtherItemsJson = 'Loaded_OtherItems.json';
  static loadCuriosityJson = 'Loaded_Curiosity.json';
  static loadTechnologyJson = 'Loaded_Technology.json';
  static loadRefineryJson = 'Loaded_Refinery.json';
  // external
  static externalLinkCVWebsite = 'CV_Website';
  static externalLinkPersonalBlog = 'Personal_Blog';
  static externalLinkBuyMeACoffee = 'BuyMeACoffee';
  static externalLinkPayPal = 'PayPal';
  static externalLinkPatreon = 'Patreon';
  static externalLinkkofi = 'Ko-fi';
  static externalLinkKurtLourensEmail = 'Email_hi@kurtlourens.com';
  static externalLinkGitHubGeneral = 'Go_to_General_Repository';
  static externalLinkGitHubLanguage = 'Go_to_Language_Repository';
  static externalLinkBat = 'BraveRewards';
  static externalLinkOpenCollective = 'OpenCollective';
}
